name: duplicate_detector
description: Duplicate Image Detection App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # For picking images from gallery/camera
  image_picker: ^1.0.7

  # For image processing (resize, grayscale)
  image: ^4.1.4

  # For file path management
  path_provider: ^2.1.2

  # For storing hashes locally
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true